[package]
name = "merge_sort"
version = "0.1.0"
authors = ["Aitzhanov Ivan <aitvann@gmail.com>"]
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
rand = "0.8"

[[bench]]
name = "random_ints"
harness = false
